let translationEN = {
    "InvalidSecurityCode": "Invalid security code",
    "Pleasetryagain": "Please try again.",
    "Invaliddata": "Invalid data",
    "Allownumbersonly": "Allow numbers only",
    "Minimumtopup1bahtormore": "Minimum top-up is 1 baht or more",
    "CreateCodeupto1000Codesatatime": "Create up to 1000 codes at a time",
    "CreatingCode": "Creating code...",
    "Codegenerated": "Code generated",
    "Codehasbeengeneratedsuccessfully": "Code has been generated successfully",
    "Cannotlogin": "Cannot login",
    "Invalidemailorpassword": "Invalid username or password!",
    "Connecting": "Connecting...",
    "Successfullyloggedin": "Successfully logged in",
    "LogginginPleasewaitamoment": "Logging in. Please wait a moment.",
    "Invalidinformation": "Invalid information",
    "SystemValidation": "System Validation",
    "AnErrorHasOccurred": "An error has occurred. Please contact support",
    "Error": "Error!",
    "Success": "Success!",
    "Donesuccessfully": "Done successfully.",
    "Warning": "Warning!",
    "Pleasenote": "Please note!",
    "Unabletotopup": "Unable to top up",
    "Codehasalreadybeenused": "Code has already been used or invalid credit code",
    "Successfullytoppedup": "Successfully topped up",
    "CreditRemainingUnit": "Remaining credit {{coin}} units",
    "Thenewpasswordsdonotmatch": "The new passwords do not match",
    "Passwordchanged": "Password changed",
    "TooManyRequests": "Too many requests",
    "Unauthorized": "Unauthorized",
    "RoleAdmin": "Administrator",
    "RoleCustomer": "User",
    "RoleSuperAdmin": "Super Administrator",
    "AddedUser": "User account created successfully",
    "ExistsUser": "Account already registered in the system. Please log in or register with another email",
    "StatusEnum_Actived": "Active",
    "StatusEnum_Deleted": "Locked",
    "StatusEnum_Blocked": "Blocked",
    "StatusEnum_UnBlocked": "Unblocked",
    "DeletedMemberSuccess": "User deleted successfully. Automatically return after notification",
    "EditedMemberSuccess": "User edited successfully.",
    "NotEnoughCoin": "Not enough coins to view the next result. Please top up",
    "AllowChooseOneFile": "Only allow choosing 1 file",
    "UploadFormulaFileSuccess": "Upload formula file successfully",
    "PendingResult": "Pending result...",
    "GetSuccessResult": "Result available",
    "NotEnoughCoinToGen1Code": "Not enough coins to generate code",
    "NotEnoughCoinToGenAll": "Not enough coins to generate all codes, only some codes will be generated",
    "TokenNotNull": "New token cannot be empty",
    "TokenUpdateSuccess": "Token updated successfully",
    "AccountDeleted": "Account has been locked. Contact admin for further assistance",
    "InvalidBetMoney": "Please enter the bet amount",
    "NotAllowNull": "{{titleField}} cannot be empty",
    "FieldTooShort": "{{titleField}} is too short. Please enter a valid value",
    "FieldvalueMissing": "Incorrect data for {{titleField}}. Please enter a valid value",
    "RepasswordNotMap": "The re-entered password does not match. Please enter again",
    "PasswordIncorrect": "Incorrect password. Please check again",
    "UpdatedLanguageDefault": "Successfully changed default language",
    "UpdatedManagerSuccess": "Successfully updated",
    "MinChatRandomNotOverMax": "The start time for random chat must not be greater than the end time for random chat.",
    "MaxChatRandomNotUnderMin": "The end time for random chat must not be less than the start time for random chat.",
    "MinViewRandomNotOverMax": "The start time for random view must not be greater than the end time for view chat.",
    "MaxViewRandomNotUnderMin": "The end time for random view chat must not be less than the start time for view chat.",
    "MinViewNotOverMax": "The minimum view count must not be greater than the maximum view count.",
    "MaxViewNotUnderMin": "The maximum view count must not be less than the minimum view count.",
    "AddMessageTemplateSuccess": "Successfully added message template.",
    "DeleteMessageTemplateSuccess": "Successfully deleted message template.",
    "UpdateMessageTemplateSuccess": "Successfully updated message template.",
    "UpdateChatConfigSuccess": "Successfully updated chat configuration.",
    "BetMoneyMustOverZero": "The bet amount must be greater than 0",
    "SomeRecordExisted": "Successfully added some parts, some records already exist",
    "InsertAll": "Successfully inserted all records",
    "FileEmpty": "Empty file or incorrect format",
    "Maintain": "Maintain",
    "TableMaintain": "Table is in maintainent"
};