let translationKR = {
    "InvalidSecurityCode": "잘못된 보안 코드",
    "Pleasetryagain": "다시 시도해 주세요.",
    "Invaliddata": "유효하지 않은 데이터",
    "Allownumbersonly": "숫자만 허용",
    "Minimumtopup1bahtormore": "최소 충전 금액은 1바트 이상입니다.",
    "CreateCodeupto1000Codesatatime": "한 번에 최대 1000개의 코드를 생성하세요.",
    "CreatingCode": "코드 생성 중...",
    "Codegenerated": "코드가 생성되었습니다.",
    "Codehasbeengeneratedsuccessfully": "코드가 성공적으로 생성되었습니다.",
    "Cannotlogin": "로그인할 수 없습니다",
    "Invalidemailorpassword": "사용자 이름 또는 비밀번호가 잘못되었습니다!",
    "Connecting": "연결 중...",
    "Successfullyloggedin": "성공적으로 로그인되었습니다.",
    "LogginginPleasewaitamoment": "로그인 중입니다. 잠시만 기다려주세요.",
    "Invalidinformation": "잘못된 정보",
    "SystemValidation": "시스템 유효성 검사",
    "AnErrorHasOccurred": "오류가 발생했습니다. 지원팀에 문의하세요.",
    "Error": "오류!",
    "Success": "성공!",
    "Donesuccessfully": "성공적으로 완료되었습니다.",
    "Warning": "경고!",
    "Pleasenote": "참고해주세요!",
    "Unabletotopup": "충전할 수 없습니다.",
    "Codehasalreadybeenused": "코드가 이미 사용되었거나 유효하지 않은 신용 코드입니다.",
    "Successfullytoppedup": "성공적으로 충전되었습니다.",
    "CreditRemainingUnit": "남은 크레딧 {{coin}} 단위",
    "Thenewpasswordsdonotmatch": "새 비밀번호가 일치하지 않습니다.",
    "Passwordchanged": "비밀번호가 변경되었습니다.",
    "TooManyRequests": "요청이 너무 많습니다.",
    "Unauthorized": "무단",
    "RoleAdmin": "관리자",
    "RoleCustomer": "사용자",
    "RoleSuperAdmin": "최고 관리자",
    "AddedUser": "사용자 계정이 성공적으로 생성되었습니다.",
    "ExistsUser": "시스템에 이미 등록된 계정입니다. 로그인하거나 다른 이메일로 등록하세요.",
    "StatusEnum_Actived": "활동적인",
    "StatusEnum_Deleted": "잠김",
    "StatusEnum_Blocked": "막힌",
    "StatusEnum_UnBlocked": "차단 해제됨",
    "DeletedMemberSuccess": "사용자가 삭제되었습니다. 알림 후 자동 복귀",
    "EditedMemberSuccess": "사용자가 성공적으로 편집했습니다.",
    "NotEnoughCoin": "다음 결과를 보기에는 코인이 부족합니다. 충전해주세요",
    "AllowChooseOneFile": "1개의 파일만 선택할 수 있습니다.",
    "UploadFormulaFileSuccess": "수식 파일을 성공적으로 업로드했습니다.",
    "PendingResult": "결과 보류 중...",
    "GetSuccessResult": "결과 확인 가능",
    "NotEnoughCoinToGen1Code": "코드를 생성하기에 코인이 충분하지 않습니다.",
    "NotEnoughCoinToGenAll": "모든 코드를 생성하기에는 코인이 부족하여 일부 코드만 생성됩니다.",
    "TokenNotNull": "새 토큰은 비워둘 수 없습니다.",
    "TokenUpdateSuccess": "토큰이 성공적으로 업데이트되었습니다.",
    "AccountDeleted": "계정이 잠겼습니다. 추가 지원이 필요하면 관리자에게 문의하세요.",
    "InvalidBetMoney": "베팅금액을 입력해주세요",
    "NotAllowNull": "{{titleField}}은(는) 비워둘 수 없습니다.",
    "FieldTooShort": "{{titleField}}이(가) 너무 짧습니다. 유효한 값을 입력하십시오.",
    "FieldvalueMissing": "{{titleField}}에 대한 데이터가 잘못되었습니다. 유효한 값을 입력하십시오.",
    "RepasswordNotMap": "다시 입력한 비밀번호가 일치하지 않습니다. 다시 입력해주세요",
    "PasswordIncorrect": "잘못된 비밀번호. 다시 확인 해주세요",
    "UpdatedLanguageDefault": "기본 언어를 성공적으로 변경했습니다.",
    "UpdatedManagerSuccess": "성공적으로 업데이트되었습니다.",
    "MinChatRandomNotOverMax": "무작위 채팅의 시작 시간은 무작위 채팅의 종료 시간보다 이후일 수 없습니다.",
    "MaxChatRandomNotUnderMin": "무작위 채팅 종료 시간은 무작위 채팅 시작 시간보다 늦어서는 안 됩니다.",
    "MinViewRandomNotOverMax": "무작위 보기의 시작 시간은 채팅 보기의 종료 시간보다 이후일 수 없습니다.",
    "MaxViewRandomNotUnderMin": "랜덤 뷰 채팅의 종료 시간은 뷰 채팅의 시작 시간보다 늦어서는 안 됩니다.",
    "MinViewNotOverMax": "최소 조회수는 최대 조회수보다 클 수 없습니다.",
    "MaxViewNotUnderMin": "최대 조회수는 최소 조회수보다 작을 수 없습니다.",
    "AddMessageTemplateSuccess": "메시지 템플릿을 성공적으로 추가했습니다.",
    "DeleteMessageTemplateSuccess": "메시지 템플릿을 성공적으로 삭제했습니다.",
    "UpdateMessageTemplateSuccess": "메시지 템플릿이 성공적으로 업데이트되었습니다.",
    "UpdateChatConfigSuccess": "채팅 구성이 성공적으로 업데이트되었습니다.",
    "BetMoneyMustOverZero": "베팅 금액은 0보다 커야 합니다.",
    "SomeRecordExisted": "일부 부분을 성공적으로 추가했습니다. 일부 기록이 이미 존재합니다.",
    "InsertAll": "모든 레코드를 성공적으로 삽입했습니다.",
    "FileEmpty": "파일이 비어 있거나 형식이 잘못되었습니다.",
    "Maintain": "유지하다",
    "TableMaintain": "테이블은 유지 관리 중입니다."
};