let translationTH = {
    "InvalidSecurityCode": "รหัสความปลอดภัยไม่ถูกต้อง",
    "Pleasetryagain": "โปรดลองอีกครั้ง",
    "Invaliddata": "ข้อมูลไม่ถูกต้อง",
    "Allownumbersonly": "อนุญาตเฉพาะตัวเลขเท่านั้น",
    "Minimumtopup1bahtormore": "เติมเงินขั้นต่ำ 1 บาทหรือมากกว่า",
    "CreateCodeupto1000Codesatatime": "สร้างรหัสได้สูงสุด 1000 รหัสต่อครั้ง",
    "CreatingCode": "กำลังสร้างรหัส...",
    "Codegenerated": "รหัสถูกสร้าง",
    "Codehasbeengeneratedsuccessfully": "รหัสถูกสร้างเรียบร้อย",
    "Cannotlogin": "ไม่สามารถเข้าสู่ระบบได้",
    "Invalidemailorpassword": "บัญชีหรือรหัสผ่านไม่ถูกต้อง!",
    "Connecting": "กำลังเชื่อมต่อ...",
    "Successfullyloggedin": "เข้าสู่ระบบเรียบร้อย",
    "LogginginPleasewaitamoment": "กำลังเข้าสู่ระบบ โปรดรอสักครู่",
    "Invalidinformation": "ข้อมูลไม่ถูกต้อง",
    "SystemValidation": "การตรวจสอบระบบ",
    "AnErrorHasOccurred": "เกิดข้อผิดพลาด โปรดติดต่อฝ่ายสนับสนุน",
    "Error": "ข้อผิดพลาด!",
    "Success": "สำเร็จ!",
    "Donesuccessfully": "สำเร็จแล้ว",
    "Warning": "คำเตือน!",
    "Pleasenote": "โปรดทราบ!",
    "Unabletotopup": "ไม่สามารถเติมเงินได้",
    "Codehasalreadybeenused": "รหัสถูกใช้แล้วหรือรหัสเครดิตไม่ถูกต้อง",
    "Successfullytoppedup": "เติมเงินเรียบร้อย",
    "CreditRemainingUnit": "ยอดเครดิตที่เหลือ: {{coin}} หน่วย",
    "Thenewpasswordsdonotmatch": "รหัสผ่านใหม่ไม่ตรงกัน",
    "Passwordchanged": "เปลี่ยนรหัสผ่านแล้ว",
    "TooManyRequests": "คำขอมากเกินไป",
    "Unauthorized": "ไม่ได้รับอนุญาต",
    "RoleAdmin": "ผู้ดูแลระบบ",
    "RoleCustomer": "ผู้ใช้",
    "RoleSuperAdmin": "ผู้ดูแลระบบสูงสุด",
    "AddedUser": "สร้างบัญชีผู้ใช้เรียบร้อย",
    "ExistsUser": "บัญชีได้ลงทะเบียนในระบบแล้ว โปรดเข้าสู่ระบบหรือลงทะเบียนด้วยอีเมลอื่น",
    "StatusEnum_Actived": "ใช้งาน",
    "StatusEnum_Deleted": "ล็อก",
    "StatusEnum_Blocked": "ถูกบล็อก",
    "StatusEnum_UnBlocked": "ยกเลิกการบล็อก",
    "DeletedMemberSuccess": "ลบผู้ใช้เรียบร้อย กลับมาโดยอัตโนมัติหลังจากการแจ้งเตือน",
    "EditedMemberSuccess": "แก้ไขผู้ใช้เรียบร้อย",
    "NotEnoughCoin": "ไม่มีเหรียญเพียงพอเพื่อดูผลลัพธ์ถัดไป โปรดเติมเงิน",
    "AllowChooseOneFile": "อนุญาตให้เลือกไฟล์เพียงหนึ่งไฟล์",
    "UploadFormulaFileSuccess": "อัปโหลดไฟล์สูตรเรียบร้อย",
    "PendingResult": "รอผลลัพธ์...",
    "GetSuccessResult": "ได้รับผลลัพธ์เรียบร้อย",
    "NotEnoughCoinToGen1Code": "ไม่มีเหรียญเพียงพอในการสร้างรหัส",
    "NotEnoughCoinToGenAll": "ไม่มีเหรียญเพียงพอในการสร้างรหัสทั้งหมด เฉพาะการสร้างบางรหัสเท่านั้น",
    "TokenNotNull": "โทเค็นใหม่ต้องไม่เว้นว่าง",
    "TokenUpdateSuccess": "อัปเดตโทเค็นเรียบร้อย",
    "AccountDeleted": "บัญชีถูกล็อกแล้ว ติดต่อผู้ดูแลระบบ",
    "InvalidBetMoney": "กรุณากรอกจำนวนเงินเดิมพัน",
    "NotAllowNull": "{{titleField}} ต้องไม่เว้นว่าง",
    "FieldTooShort": "{{titleField}} สั้นเกินไป กรุณากรอกค่าที่ถูกต้อง",
    "FieldvalueMissing": "{{titleField}} ป้อนข้อมูลไม่ถูกต้องตามที่กำหนด กรุณากรอกค่าที่ถูกต้อง",
    "RepasswordNotMap": "รหัสผ่านที่ป้อนอีกครั้งไม่ตรงกัน กรุณาป้อนใหม่",
    "PasswordIncorrect": "รหัสผ่านไม่ถูกต้อง กรุณาตรวจสอบอีกครั้ง",
    "UpdatedLanguageDefault": "เปลี่ยนภาษาเริ่มต้นเรียบร้อยแล้ว",
    "UpdatedManagerSuccess": "อัปเดตสำเร็จแล้ว",
    "MinChatRandomNotOverMax": "เวลาเริ่มสุ่มแชทต้องไม่มากกว่าเวลาสิ้นสุดสุ่มแชท",
    "MaxChatRandomNotUnderMin": "เวลาสิ้นสุดสุ่มแชทต้องไม่น้อยกว่าเวลาเริ่มสุ่มแชท",
    "MinViewRandomNotOverMax": "เวลาเริ่มสุ่มมุมมองต้องไม่มากกว่าเวลาสิ้นสุดมุมมองแชท",
    "MaxViewRandomNotUnderMin": "เวลาสิ้นสุดมุมมองแชทต้องไม่น้อยกว่าเวลาเริ่มสุ่มมุมมองแชท",
    "MinViewNotOverMax": "จำนวนมุมมองขั้นต่ำต้องไม่มากกว่าจำนวนมุมมองสูงสุด",
    "MaxViewNotUnderMin": "จำนวนมุมมองสูงสุดต้องไม่น้อยกว่าจำนวนมุมมองขั้นต่ำ",
    "AddMessageTemplateSuccess": "เพิ่มเทมเพลตข้อความสำเร็จ",
    "DeleteMessageTemplateSuccess": "ลบเทมเพลตข้อความสำเร็จ",
    "UpdateMessageTemplateSuccess": "อัปเดตเทมเพลตข้อความสำเร็จ",
    "UpdateChatConfigSuccess": "อัปเดตการตั้งค่าแชทสำเร็จ",
    "BetMoneyMustOverZero": "จำนวนเงินเดิมพันต้องมากกว่า 0",
    "SomeRecordExisted": "เพิ่มส่วนบางส่วนสำเร็จแล้ว บางบันทึกมีอยู่แล้ว",
    "InsertAll": "เพิ่มบันทึกทั้งหมดสำเร็จ",
    "FileEmpty": "ไฟล์ว่างเปล่าหรือรูปแบบไม่ถูกต้อง",
    "Maintain": "บำรุงรักษา",
    "TableMaintain": "ตารางอยู่ในการบำรุงรักษา"
}