let translationVI = {
    "InvalidSecurityCode": "Mã bảo mật không hợp lệ",
    "Pleasetryagain": "Vui lòng thử lại.",
    "Invaliddata": "Dữ liệu không hợp lệ",
    "Allownumbersonly": "Chỉ cho phép nhập số",
    "Minimumtopup1bahtormore": "Nạp tối thiểu 1 baht hoặc nhiều hơn",
    "CreateCodeupto1000Codesatatime": "Tạo Mã lên đến 1000 Mã mỗi lần",
    "CreatingCode": "Đang tạo Mã...",
    "Codegenerated": "Mã được tạo",
    "Codehasbeengeneratedsuccessfully": "Mã đã được tạo thành công",
    "Cannotlogin": "Không thể đăng nhập",
    "Invalidemailorpassword": "Tài khoản hoặc mật khẩu không hợp lệ!",
    "Connecting": "Đang kết nối...",
    "Successfullyloggedin": "Đăng nhập thành công",
    "LogginginPleasewaitamoment": "Đang đăng nhập. Vui lòng đợi một lát.",
    "Invalidinformation": "Thông tin không hợp lệ",
    "SystemValidation": "Xác nhận Hệ thống",
    "AnErrorHasOccurred": "Đã xảy ra lỗi. Vui lòng liên hệ hỗ trợ",
    "Error": "Lỗi!",
    "Success": "Thành công!",
    "Donesuccessfully": "Hoàn thành thành công.",
    "Warning": "Cảnh báo!",
    "Pleasenote": "Vui lòng lưu ý!",
    "Unabletotopup": "Không thể nạp tiền",
    "Codehasalreadybeenused": "Mã đã được sử dụng hoặc Mã tín dụng không hợp lệ",
    "Successfullytoppedup": "Nạp tiền thành công",
    "CreditRemainingUnit": "Số dư Tín dụng {{coin}} đơn vị",
    "Thenewpasswordsdonotmatch": "Mật khẩu mới không khớp",
    "Passwordchanged": "Mật khẩu đã được thay đổi",
    "TooManyRequests": "Quá nhiều yêu cầu",
    "Unauthorized": "Không được ủy quyền",
    "RoleAdmin": "Quản trị viên",
    "RoleCustomer": "Người sử dụng",
    "RoleSuperAdmin": "Quản trị viên cấp cao",
    "AddedUser": "Tạo tài khoản thành công",
    "ExistsUser": "Tài khoản đã được đăng kí trên hệ thống. Vui lòng đăng nhập hoặc đăng kí với email khác",
    "StatusEnum_Actived": "Hoạt động",
    "StatusEnum_Deleted": "Khóa",
    "StatusEnum_Blocked": "Chặn",
    "StatusEnum_UnBlocked": "Mở chặn",
    "DeletedMemberSuccess": "Xóa người dùng thành công. Tự động quay lại sau thông báo",
    "EditedMemberSuccess": "Sửa người dùng thành công.",
    "NotEnoughCoin": "Không đủ coin để xem kết quả tiếp theo. Vui lòng nạp thêm",
    "AllowChooseOneFile": "Chỉ cho phép chọn 1 file",
    "UploadFormulaFileSuccess": "Upload file công thức thành công",
    "PendingResult": "Đang chờ kết quả...",
    "GetSuccessResult": "Đã có kết quả",
    "NotEnoughCoinToGen1Code": "Không đủ coin để tạo mã",
    "NotEnoughCoinToGenAll": "Không đủ coin để tạo tất cả các mã, chỉ tạo được một số mã",
    "TokenNotNull": "Token mới không được để trống",
    "TokenUpdateSuccess": "Token thay đổi thành công",
    "AccountDeleted": "Tài khoản đã bị khóa. Liên hê với admin để xử lý",
    "InvalidBetMoney": "Vui lòng nhập số tiền cược",
    "NotAllowNull": "{{titleField}} không thể để trống",
    "FieldTooShort": "{{titleField}} quá ngắn. Vui lòng nhập một giá trị hợp lệ",
    "FieldvalueMissing": "Dữ liệu không đúng cho {{titleField}}. Vui lòng nhập một giá trị hợp lệ",
    "RepasswordNotMap": "Mật khẩu nhập lại không khớp. Vui lòng nhập lại",
    "PasswordIncorrect": "Mật khẩu không đúng. Vui lòng kiểm tra lại",
    "UpdatedLanguageDefault": "Đổi ngôn ngữ mặc định thành công",
    "UpdatedManagerSuccess": "Cập nhật thông tin thành công",
    "MinChatRandomNotOverMax": "Thời gian bắt đầu random chat không được lớn hơn Thời gian kết thúc random chat",
    "MaxChatRandomNotUnderMin": "Thời gian kết thúc random chat không được nhỏ hơn Thời gian bắt đầu random chat",
    "MinViewRandomNotOverMax": "Thời gian bắt đầu random view không được lớn hơn Thời gian  kết thúc view chat",
    "MaxViewRandomNotUnderMin": "Thời gian kết thúc view chat không được nhỏ hơn Thời gian bắt đầu view chat",
    "MinViewNotOverMax": "View nhỏ nhất không được lớn hơn View lớn nhất",
    "MaxViewNotUnderMin": "View lớn nhất không được nhỏ hơn View nhỏ nhất",
    "AddMessageTemplateSuccess":"Thêm tin nhắn mẫu thành công",
    "DeleteMessageTemplateSuccess": "Xóa tin nhắn mẫu thành công",
    "UpdateMessageTemplateSuccess": "Cập nhật tin nhắn mẫu thành công",
    "UpdateChatConfigSuccess": "Cập nhật cấu hình tin nhắn thành công",
    "BetMoneyMustOverZero": "Số tiền cược phải lớn hơn 0",
    "UserNameNull": "UserName không được bỏ trống",
    "UserNameExists": "UserName đã tồn tại hoặc trùng với UserName thật",
    "UpdateUserTemplateSuccess": "Cập nhật UserName thành công",
    "DeleteUserTemplateSuccess": "Xóa UserName thành công",
    "AddUserTemplateSuccess": "Thêm UserName thành công",
    "SomeRecordExisted": "Thêm một phần thành công, một số bản ghi đã tồn tại",
    "InsertAll": "Thêm tất cả bản ghi thành công",
    "FileEmpty": "File trống hoặc sai định dạng",
    "Maintain": "Bảo trì",
    "TableMaintain": "Bàn đang bảo trì"
}